### ISSUE TITLE
Лабораторная №4 Вопросы 

### ISSUE THREAD

**Issue by readysloth** [DizelforClaSS/ArhVS_Lab#4]
+ Какой ограничитель на расположение операнда стоит написать, чтобы дать компилятору наибольшую свободу в применении оптимизаций?
+ Скажите, а в чем плюсы использования во вставках имен переменных, а не конкретных регистров?
+ Когда стоит использовать volatile ?

**Comment by Romarado** [comment]
- **Какой ограничитель на расположение операнда стоит написать, чтобы дать компилятору наибольшую свободу в применении оптимизаций** Ответ: O3

- ·        -O0 (O ноль) - это самые простые и примитивные оптимизации.
- ·        -O1 - более сильные оптимизации.
- ·        -O2 - оптимизировать все, что можно, но только проверенные и надежные оптимизации.
- ·         -O3 - жесткая и насильная оптимизация, применяются экспериментальные методы.


- **Скажите, а в чем плюсы использования во вставках имен переменных, а не конкретных регистров?** Ответ:

Написание кода с использованием переменных упрощает жизнь программисту, освобождая его оперативную память. Не нужно держать в голове, в каком регистре, что именно лежит. Если мы работаем с большим количеством данных, держать в голове приходится и без того много информации

- **Когда стоит использовать volatile ?** Ответ:

Ключевое слово volatile языка C это квалификатор, который добавляется к декларации переменной (квалификатор типа переменной, наподобие квалификатора const). Оно говорит компилятору, что значение переменной может быть изменено в любой момент времени - без каких-либо видимых для компилятора действий кода, окружающего переменную. Компилятор не должен трогать эту переменную в процессе оптимизации кода.
